# Generated by Django 5.1.5 on 2025-02-03 17:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_movies_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5, 'Avaliação máxima com 5 estrelas'), django.core.validators.MinValueValidator(0, 'Avaliação mínima com 0 estrelas')])),
                ('comment', models.TextField(blank=True, max_length=150, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_movie', to='movies.movies')),
            ],
        ),
    ]
