# Generated by Django 5.1.5 on 2025-02-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('nationality', models.CharField(choices=[('USA', 'Estados Unidos'), ('BRA', 'Brazil'), ('DEU', 'Alemanha'), ('CAN', 'Canadá'), ('CHN', 'China')], max_length=100)),
            ],
        ),
    ]
