# Generated by Django 5.1.5 on 2025-02-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='resume',
            field=models.TextField(default='Descrição do filme', max_length=300),
        ),
    ]
